

services:
  postgres:
    image: postgres:17
    container_name: auth-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostoassignment

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-cli:
    build: .
    container_name: auth-cli

    depends_on:
      - postgres

    stdin_open: true
    tty: true

    env_file:
      - .env

volumes:
  postgres_data: